/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CategoryID = IDL.Nat;
export const RuleID = IDL.Nat;
export const Time = IDL.Int;
export const TransactionID = IDL.Nat;

export const idlService = IDL.Service({
  'addCategory' : IDL.Func([IDL.Text], [CategoryID], []),
  'addRule' : IDL.Func([IDL.Text, CategoryID], [RuleID], []),
  'addTransaction' : IDL.Func(
      [IDL.Float64, IDL.Text, Time, IDL.Opt(CategoryID)],
      [TransactionID],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CategoryID = IDL.Nat;
  const RuleID = IDL.Nat;
  const Time = IDL.Int;
  const TransactionID = IDL.Nat;
  
  return IDL.Service({
    'addCategory' : IDL.Func([IDL.Text], [CategoryID], []),
    'addRule' : IDL.Func([IDL.Text, CategoryID], [RuleID], []),
    'addTransaction' : IDL.Func(
        [IDL.Float64, IDL.Text, Time, IDL.Opt(CategoryID)],
        [TransactionID],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };